### PR TITLE
Added death packet

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by firebolt55439** [comment]
I'm having trouble reproducing this on my computer for some reason - it does not seem that a death packet is sent by the client to the server with a last value of 21. 

Could you verify that it works on your computer? Are you perhaps doing a different game mode (e.g. Team DM, Domination, etc.)? @Maplicant

**Comment by hxxr** [comment]
I've tested all the game modes, and it doesn't seem like any packets are sent upon death. Maybe this was just a coincidence, like when there was two packets when upgrading Health Regen.

**Comment by firebolt55439** [comment]
The client doesn't seem to send the server any special packets upon death, but there must be some packet sent by the server to the client indicating that your tank died. I'll look into that (maybe even clear up some server --> client communication on the way).

**Comment by ghost** [comment]
I think it was just a coincidence. I should have tested it more thoroughly. I agree with @firebolt55439 though that there has to be something that activates the respawn screen. It might do something like `if (health < 0)`, but then we would have to reverse-engineer the health system first.

**Comment by firebolt55439** [comment]
That's certainly possible, but I'm still holding out hope there's some "nice" packet sent by the server to the client upon death 😄

**Comment by hxxr** [comment]
You know what? I'll work on this too.

Edit: Right now I'm 75% sure that if there are packets for death and/or health, it would be from the server, because the client would send the server info about the current tank, but it has no idea where the other bullets and tanks are.

**Comment by hxxr** [comment]
I think we should close this and post our findings on a discussion.

**Comment by firebolt55439** [comment]
Agreed.

**Comment by firebolt55439** [comment]
@hxxr Would you like to open the discussion?

**Comment by hxxr** [comment]
#15

**Pull request closed without merging**
