### PR TITLE
Added recognition for server uptime

### PR DESCRIPTION
**Pull request by hxxr**
This script will now automatically retrieve server uptime (in ticks) and save it as the variable `uptime`, although this still needs to be verified.

I also do need help figuring out how long a "tick" is.

### CODE REVIEW

**Comment by hxxr** [comment]
For some reason, this only works on FFA and Team DM... I'll fix that.

**Comment by hxxr** [comment]
Ok, I fixed it, do you think anything needs to be changed?

**Comment by hxxr** [comment]
...Hello? Anyone there?

**Comment by firebolt55439** [comment]
That's actually very interesting - a "tick" can't be very long, most likely less than a minute. Let me do some further testing with the extension.

**Comment by hxxr** [comment]
I used my phone's stopwatch and found out that 127 "ticks" is around 5 seconds, but there might be a way to get a more exact result.

**Comment by hxxr** [comment]
Well, I did some testing, and I found out that 100 ticks should be exactly 4 seconds, so that means 1 tick should be 40 milliseconds.

**Pull request merged**
